[project]
name = "wf-demo"
version = "2.0.0"
description = "The open DISTINGUISH Workflow"
authors = [{ name = "Kristian Fossum", email = "krfo@norceresearch.no" }]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "scipy",
    "seaborn",
    "streamlit",
    "plotly",
    "kaleido",
    "torch==2.13.0",
    "torchvision==0.28.0",
    "PET-GAN-LOG @ git+https://github.com/geosteering-no/PET-GAN-LOG.git",
    "pathoptim @ git+https://github.com/geosteering-no/DSUP.git",
    "GAN-EM-model @ git+https://github.com/geosteering-no/GAN-EM-model.git@feat/update_weights",
    "udar_proxi @ git+https://github.com/KriFos1/UTA-proxy-final.git@2fdb9a356ad2cf495c04eb402f272724cd9f00dd",
    "PET @ git+https://github.com/Python-Ensemble-Toolbox/PET.git@5660cf20ad70707704727689dee3ddd229646696",
    "geostat @ git+https://github.com/Python-Ensemble-Toolbox/Geostatistics@main",
]

[project.scripts]
run_WF = "wf_demo.run_WF:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["wf_demo"]
exclude = ["data"]
